### ISSUE TITLE
Crash on "Advanced settings"

### ISSUE THREAD

**Issue by shuvashish76** [cvzi/ScreenshotTile#189]
App crashing when I click on "Advanced settings"

**Crash logs:**
```
FATAL EXCEPTION: main
Process: com.github.cvzi.screenshottile, PID: 2669
java.lang.NoSuchFieldError: No static field WEBP_LOSSY of type Landroid/graphics/Bitmap$CompressFormat; in class Landroid/graphics/Bitmap$CompressFormat; or its superclasses (declaration of 'android.graphics.Bitmap$CompressFormat' appears in /system/framework/framework.jar)
	at h1.b$a.<clinit>(Unknown Source:7)
	at h1.b.k0(SettingAdvancedFragment.kt:2)
	at h1.b.m0(SettingAdvancedFragment.kt:5)
	at h1.b.K(SettingAdvancedFragment.kt:4)
	at androidx.fragment.app.g0.n(FragmentStateManager.java:23)
	at androidx.fragment.app.g0.k(FragmentStateManager.java:9)
	at androidx.fragment.app.r0$a.c(SpecialEffectsController.java:2)
	at androidx.fragment.app.c$c.a(DefaultSpecialEffectsController.java:3)
	at androidx.fragment.app.c.b(DefaultSpecialEffectsController.java:197)
	at androidx.fragment.app.r0.c(SpecialEffectsController.java:22)
	at androidx.fragment.app.a0.B(FragmentManager.java:81)
	at androidx.fragment.app.a0.U(FragmentManager.java:10)
	at androidx.fragment.app.a0.z(FragmentManager.java:14)
	at androidx.fragment.app.a0$g.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Device details:**
App version - 1.18.2 (71)
Android version - 8.1.0

**Comment by cvzi** [comment]
Thanks for the report. I have fixed this and the update should be available in the next few days.
