### ISSUE TITLE
Width and height must be > 0

### ISSUE THREAD

**Issue by shuvashish76** [cvzi/ScreenshotTile#313]
Not sure how to reproduce this crash / 1 time crash

Crash logs:

```
FATAL EXCEPTION: main
Process: com.github.cvzi.screenshottile, PID: 6962
java.lang.IllegalArgumentException: width and height must be > 0
 at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:851)
 at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:721)
 at d.s.run(R8$$SyntheticClass:366)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Device details:
Android: 8.1.0
Model: Lenovo TB-8704X
App version: 2.1.0 (92)

**Comment by cvzi** [comment]
Thanks! Yes I have seen it in reports from Google Play Store error reporting as well. I think it happens when the image should be resized to a smaller image for the preview in the notification. I am not sure why exactly it is happening, why the width or height is 0.
But I think I already fixed it, so it will now use the image without resizing instead of crashing. 
The fix will be in version 2.2.2. F-Droid hasn't compiled that version yet even though it is two weeks old, it seems something is currently wrong at F-Droid 🫤
