### ISSUE TITLE
Android 11: AccessibilityService creates IncorrectContextUseViolation in strict mode

### ISSUE THREAD

**Issue by cvzi** [cvzi/ScreenshotTile#42]
Starting the accesibility service on Android 11 creates a VmPolicy exception

```
/com.github.cvzi.screenshottile.debug D/StrictMode: StrictMode policy violation: android.os.strictmode.IncorrectContextUseViolation: Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
      at android.os.StrictMode.onIncorrectContextUsed(StrictMode.java:2192)
      at android.app.ContextImpl.getSystemService(ContextImpl.java:1915)
      at android.accessibilityservice.AccessibilityService.getSystemService(AccessibilityService.java:2006)
      at android.accessibilityservice.AccessibilityService$2.init(AccessibilityService.java:2091)
      at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2311)
      at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:223)
      at android.app.ActivityThread.main(ActivityThread.java:7656)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
   Caused by: java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.github.cvzi.screenshottile.services.ScreenshotAccessibilityService@c1d3698
      at android.app.ContextImpl.getSystemService(ContextImpl.java:1914)
      at android.accessibilityservice.AccessibilityService.getSystemService(AccessibilityService.java:2006) 
      at android.accessibilityservice.AccessibilityService$2.init(AccessibilityService.java:2091) 
      at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2311) 
      at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44) 
      at android.os.Handler.dispatchMessage(Handler.java:106) 
      at android.os.Looper.loop(Looper.java:223) 
      at android.app.ActivityThread.main(ActivityThread.java:7656) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
/com.github.cvzi.screenshottile.debug E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.github.cvzi.screenshottile.services.ScreenshotAccessibilityService@c1d3698 Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
  java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.github.cvzi.screenshottile.services.ScreenshotAccessibilityService@c1d3698
      at android.app.ContextImpl.getSystemService(ContextImpl.java:1914)
      at android.accessibilityservice.AccessibilityService.getSystemService(AccessibilityService.java:2006)
      at android.accessibilityservice.AccessibilityService$2.init(AccessibilityService.java:2091)
      at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2311)
      at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:223)
      at android.app.ActivityThread.main(ActivityThread.java:7656)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by cvzi** [comment]
This seems to be a more general problem.
A minimal test of accessibility service creates the same error message, see https://github.com/cvzi/testaccessibility

**Comment by cvzi** [comment]
https://issuetracker.google.com/issues/175604408
