### ISSUE TITLE
1.14.1 says Accessiblity Service is disabled / Bad notification crash

### ISSUE THREAD

**Issue by linsui** [cvzi/ScreenshotTile#98]
Though Accessiblilty Service is enabled,  the app says it's disabled and doesn't work. 1.14.0 works.

**Comment by cvzi** [comment]
I see it is as well. I thought it was only a problem on Android 12 but it seems to be all Android versions (but not all phones).

Something goes wrong when creating an icon for a notification:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.cvzi.screenshottile, PID: 31065
    android.app.RemoteServiceException: Bad notification(tag=null, id=7593) posted from package com.github.cvzi.screenshottile, crashing app(uid=10322, pid=31065): Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.github.cvzi.screenshottile id=0x7f0800c7) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7604)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
I committed a version that uses a standard Android icon instead of the custom icons, that seems to fix it for now.

**Comment by linsui** [comment]
1.14.3 works well. Thanks!
