### ISSUE TITLE
Crash in 1.14.1

### ISSUE THREAD

**Issue by opk12** [cvzi/ScreenshotTile#99]
Since the upgrade to 1.14.1, a crash error message pops up instead of the app's notification to display the screenshot. However the screenshot file can be found at the expected location. There is no problem with 1.14.0. Both versions are from F-droid. This phone has Android 7.

Relevant logcat:

```
FATAL EXCEPTION: main
Process: com.github.cvzi.screenshottile, PID: ...
android.app.RemoteServiceException: Bad notification posted from package com.github.cvzi.screenshottile: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.github.cvzi.screenshottile id=...) visible user=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by cvzi** [comment]
Thanks for the report! I have submitted a temporary fix, see #98  Just waiting for F-Droid to build it.

**Comment by cvzi** [comment]
Should be fixed now

**Comment by opk12** [comment]
This is now fixed for me. Thanks!
